language: node_js
node_js:
  - "node"

deploy:
  provider: script
  script: "yarn run coverage && yarn run lint && yarn run compile"
  skip_cleanup: true
  on:
    branch: master

before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search